headers = {
        'authority': 'shop-graphql-ru.lesta.ru',
        'accept': '*/*',
        'accept-language': 'ru,en;q=0.9',
        'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjJpZ29yMl8iLCJqdGkiOiIzYmNmMGU2YmY1ODA1ZTk1NjA2ODYzZmE0MTI3YmI0OSIsImhhc19lbWFpbCI6dHJ1ZSwiZXhwIjoxNzAyNTM4NzA4LCJsYW5ndWFnZSI6InJ1Iiwic2NvcGUiOltdLCJpc3MiOiJ1cm46d2FyZ2FtaW5nOnBzcyIsImNvdW50cnkiOiJSVSIsInNwYV9pZCI6MjUxMzcyODB9.ri0xPdxkq67dCnSpuRTSH4edvs5-fYjFxsbIsvuff4U',
        'content-type': 'application/json',
        'dnt': '1',
        'origin': 'https://lesta.ru',
        'referer': 'https://lesta.ru/',
        'sec-ch-ua': '"Chromium";v="118", "YaBrowser";v="23", "Not=A?Brand";v="99"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.731 YaBrowser/23.11.1.731 Yowser/2.5 Safari/537.36',
        'x-request-id': 'e1d0d1fa-2072-4f3f-b533-35f6cfa8ee1e',
    }

headers = {
        'authority': 'shop-graphql-ru.lesta.ru',
        'accept': '*/*',
        'accept-language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjJpZ29yMl8iLCJqdGkiOiIzYmNmMGU2YmY1ODA1ZTk1NjA2ODYzZmE0MTI3YmI0OSIsImhhc19lbWFpbCI6dHJ1ZSwiZXhwIjoxNzAyNTM4NzA4LCJsYW5ndWFnZSI6InJ1Iiwic2NvcGUiOltdLCJpc3MiOiJ1cm46d2FyZ2FtaW5nOnBzcyIsImNvdW50cnkiOiJSVSIsInNwYV9pZCI6MjUxMzcyODB9.ri0xPdxkq67dCnSpuRTSH4edvs5-fYjFxsbIsvuff4U',
        'cache-control': 'no-cache',
        'content-type': 'application/json',
        'dnt': '1',
        'origin': 'https://lesta.ru',
        'pragma': 'no-cache',
        'referer': 'https://lesta.ru/',
        'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'x-request-id': 'e1d0d1fa-2072-4f3f-b533-35f6cfa8ee1e',
    }